# Generated by Django 5.2.16 on 2026-07-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_berth_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pg.pgproperty'),
        ),
    ]
