# Generated by Django 5.2.16 on 2026-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_room_pg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
