# Generated by Django 5.2.16 on 2026-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_tenant_created_at_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
