# Generated by Django 5.2.16 on 2026-07-24 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_tenant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='pg.pgproperty'),
        ),
    ]
