# Generated by Django 5.2.16 on 2026-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='whatsapp_source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
