# Generated by Django 5.2.16 on 2026-07-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_phoneotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
