// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGAd7MqGgqhYKTz2eEzcbRqseISh8gSWA',
    appId: '1:814928120470:web:8cc9f85c674720613b10b7',
    messagingSenderId: '814928120470',
    projectId: 'pg-management-703c9',
    authDomain: 'pg-management-703c9.firebaseapp.com',
    storageBucket: 'pg-management-703c9.firebasestorage.app',
    measurementId: 'G-2BNKZSESD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFf-R1lYcRywTJckIeRoUhAvaDHIweNc',
    appId: '1:814928120470:android:9ede27a8536a766f3b10b7',
    messagingSenderId: '814928120470',
    projectId: 'pg-management-703c9',
    storageBucket: 'pg-management-703c9.firebasestorage.app',
  );
}
